apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kurly-commerce
  namespace: kurly-commerce
spec:
  rules:
    - host: kurly.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kurly-frontend
                port:
                  number: 3000
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: kurly-backend
                port:
                  number: 8080
